### ISSUE TITLE
Use delegated as a form of Proxy auth

### ISSUE THREAD

**Issue by wprater** [cloudant/delegated_auth#7]
Im hoping to enable a form of proxy authentication in Cloudant.  Can I use this to create a cookie and set my user/roles from a downstream service?  

Id like to use `proxy_authentication_handler`, but it does not seem to be available.  

I found this extension, which I think is used for LDAP, but maybe it's possible to use for another downstream service before making a request to Cloudant?

**Comment by rnewson** [comment]
hi, sorry. no, this is not something we support at Cloudant.

**Comment by wprater** [comment]
thanks for the info!
